### ISSUE TITLE
Are you guys planning to have Flutter SDK too?

### ISSUE THREAD

**Issue by THALLIVA** [TuyaInc/tuya_pulsar_sdk_go#1]
-----NOT A ISSUE------

As Flutter is now in stable mode and many developers are into it, Can we have a Tuya SDK/plugin for Google Flutter too?
We would love to have a Flutter SDK or a plugin to support the Flutter Community..

Thanks and Best Wishes..

**Comment by LvBay** [comment]
I am very sorry that there is no plan to develop Flutter-sdk yet. @THALLIVA

**Comment by nashihu** [comment]
i hope tuya sdk for flutter is available..

**Comment by kasvith** [comment]
@LvBay still no flutter ?

**Comment by LvBay** [comment]
> @LvBay still no flutter ?

There are currently no plans to support flutter. In addition, this sdk is generally provided to servers running on the cloud to receive tuya device messages, and it is not recommended to use flutter-side business scenarios.

**Comment by nashihu** [comment]
> @LvBay still no flutter ?

i've implement tuya sdk for flutter using MethodChannel. But you'll also need to implement the code in Kotlin/Swift depending on your target device

**Comment by belalkaoukgi** [comment]
Hi, I'm integrating Tuya with channel flutter, but when I log in correctly, the program suddenly stops, and the error is:

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.smartlife/com.example.smartlife.Home}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

Can anyone help me with this problem

**Comment by sakinaboriwala** [comment]
Please extend support for Flutter!

**Comment by sakinaboriwala** [comment]
> > @LvBay still no flutter ?
> 
> i've implement tuya sdk for flutter using MethodChannel. But you'll also need to implement the code in Kotlin/Swift depending on your target device

I am trying the same @nashihu May I know how did you initialize the sdk in flutter project?

**Comment by nashihu** [comment]
you'll need to implement both in Android Kotlin/Java side and also in iOS Swift/Obj-C side @sakina1403 , no dart code required for initialization

just imagine working on 2 native mobile project (android&ios) but u run it using flutter

**Comment by sakinaboriwala** [comment]
Thanks @nashihu Yes I understand that but unfortunately I don't know either so I am struggling a little bit with initialisation of the SDK. Do you have any helper code I can look into?

**Comment by oojoolab** [comment]
I have experience deploying a Tuya app using Flutter. If you would like to use it as well, I can provide the Flutter SDK and an example app.


https://github.com/oojoolab/tuya_flutter_sdk

**Comment by idrisbolukbasi** [comment]
https://pub.dev/packages/tuya_home_sdk_flutter
https://pub.dev/packages/tuya_smart_home_sdk
https://pub.dev/packages/tuya_plugin

flutter pub.dev libraries links below

**Comment by anas43950** [comment]
@oojoolab I can't find any source code from the link you provided, only some screenshots and documentation

**Comment by Alvish0407** [comment]
> I have experience deploying a Tuya app using Flutter. If you would like to use it as well, I can provide the Flutter SDK and an example app.
> 
> https://github.com/oojoolab/tuya_flutter_sdk

Can you please share the source code?
