### ISSUE TITLE
Missing Acknoweldgement from Pulsar API

### ISSUE THREAD

**Issue by nk-gears** [TuyaInc/tuya_pulsar_sdk_go#5]
Thanks for the Tuya GO SDK.

We should receive some acknowledgement when the client tries to connect to the pulsar server API.

Otherwise, we don't have a clue whether the Client connection is success or failure with the Pulsar API.

This may not be the issue with SDK, But, would like to raise this whether its possible to get an acknowledgment after the successful handshake with the server.

**Comment by LvBay** [comment]
The current prompt message is indeed not friendly enough. If sdk can successfully connect to pulsar, it would be friendly to print some logs. I will update some code later.

**Comment by LvBay** [comment]
I modified some code. Now when you connect pulsar, there will be some log information.
@nk-gears

**Comment by nk-gears** [comment]
@LvBay, Thank you. It works good now and i can see the acknowledgement that the client is able to  talk to pulsar service.
